"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-19 00:20:04.920296

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('visa_status', sa.Enum('H1B', 'OPT', 'STEM_OPT', 'GC', 'GC_EAD', 'USC', 'TN', 'L1', 'H4_EAD', 'C2C', 'W2', name='visastatus'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_PROJECT', 'MARKETING', 'PLACED', 'INACTIVE', name='consultantstatus'), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=False),
    sa.Column('primary_skill', sa.String(length=120), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('years_experience', sa.Float(), nullable=False),
    sa.Column('expected_rate', sa.Float(), nullable=False),
    sa.Column('daily_bench_cost', sa.Float(), nullable=False),
    sa.Column('availability_date', sa.Date(), nullable=True),
    sa.Column('bench_start_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rate_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('min_rate', sa.Float(), nullable=False),
    sa.Column('max_rate', sa.Float(), nullable=False),
    sa.Column('demand_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact_email', sa.String(length=160), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('response_rate', sa.Float(), nullable=False),
    sa.Column('avg_response_hours', sa.Float(), nullable=False),
    sa.Column('placements_count', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('last_contacted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('immigration_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultant_id', sa.Integer(), nullable=False),
    sa.Column('visa_type', sa.Enum('H1B', 'OPT', 'STEM_OPT', 'GC', 'GC_EAD', 'USC', 'TN', 'L1', 'H4_EAD', 'C2C', 'W2', name='visastatus'), nullable=False),
    sa.Column('work_auth_start', sa.Date(), nullable=True),
    sa.Column('work_auth_end', sa.Date(), nullable=True),
    sa.Column('ead_expiry', sa.Date(), nullable=True),
    sa.Column('i94_expiry', sa.Date(), nullable=True),
    sa.Column('lca_filed', sa.Boolean(), nullable=False),
    sa.Column('worksite_location', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['consultant_id'], ['consultants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('client', sa.String(length=160), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('remote', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('min_rate', sa.Float(), nullable=False),
    sa.Column('max_rate', sa.Float(), nullable=False),
    sa.Column('visa_requirements', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultant_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('parsed_skills', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultant_id'], ['consultants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultant_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'SHORTLISTED', 'INTERVIEW', 'OFFER', 'PLACED', 'REJECTED', name='submissionstatus'), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('rtr_signed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultant_id'], ['consultants.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('panel', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviews')
    op.drop_table('submissions')
    op.drop_table('resumes')
    op.drop_table('jobs')
    op.drop_table('immigration_records')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_table('rate_cards')
    op.drop_table('consultants')
    # ### end Alembic commands ###
